name: Release

on:
  push:
    paths: 
      - package.json
    branches:
      - main

jobs:

  publish:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Get Package Version
        uses: EndBug/version-check@v2.1.0
        id: version

      - name: Publish Package
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          access: public